In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
pd.set_option("display.max_columns",None)

In [3]:
train_df = pd.read_excel("Datasets/interview_train.xlsx")
test_df = pd.read_excel("Datasets/interview_test.xlsx")

In [4]:
train_df.head()

,Interview Id,Candidate Id,Interviewer Id,Profile,S.L.R.C,S.L.R.I,A.T.T,L.M.I,L.M.C,S.R,L.J.T.C,L.J.T.I,N.I.C,N.I.I,S.P.I,S.P.C,L.A.C,L.A.I,Q.A,P.E.I,P.E.C,COMPLIANCE Ratio,Interview duration,Interviewer Intro,Candidate into,Opp to ask,Status
0,6.913030e+11,2.655774e+09,194,Developer,0.98,0.02,53,88,93,32,88,106,41,66,42,47,13,15,6,Neutral,Neutral,98,37,No,Yes,Yes,Consider
1,9.214326e+11,7.123846e+08,234,Sales,0.67,0.33,51,53,44,36,93,313,28,62,32,52,5,15,4,Neutral,Negative,54,33,No,No,Yes,Consider
2,4.718839e+10,8.445533e+08,267,Program Manager,0.81,0.19,60,77,75,54,52,67,26,14,57,34,4,7,3,Positive,Positive,31,58,No,Yes,No,Consider
3,9.943741e+11,6.511106e+09,199,Marketing,0.69,0.31,93,42,103,49,115,166,62,55,65,75,10,10,7,Positive,Negative,24,35,No,Yes,No,Consider
4,3.509007e+11,3.487001e+09,221,QA Automation,0.57,0.43,44,44,119,66,190,394,7,32,36,74,13,7,3,Negative,Positive,73,60,Yes,Yes,No,Consider

In [5]:
test_df.head()

,Interview Id,Candidate Id,Interviewer Id,Profile,S.L.R.C,S.L.R.I,A.T.T,L.M.I,L.M.C,S.R,L.J.T.C,L.J.T.I,N.I.C,N.I.I,S.P.I,S.P.C,L.A.C,L.A.I,Q.A,P.E.I,P.E.C,COMPLIANCE Ratio,Interview duration,Interviewer Intro,Candidate into,Opp to ask
0,702127796635,2.381365e+09,229,Product Manager,0.52,0.48,103,53,77,30,26.0,287,8,22,69.0,88,5,19.0,4.0,Positive,Negative,24.0,49,Yes,Yes,Yes
1,613490569071,8.428514e+08,194,Product Manager,0.87,0.13,54,57,57,68,179.0,253,62,40,47.0,81,1,9.0,7.0,Positive,Neutral,99.0,24,No,Yes,Yes
2,759998772623,7.681665e+09,266,QA Automation,0.60,0.40,50,117,93,36,137.0,31,40,52,57.0,13,7,15.0,3.0,Negative,Positive,16.0,16,Yes,No,Yes
3,391760082113,6.627808e+09,256,HR,0.52,0.48,102,114,66,31,176.0,242,69,66,59.0,10,10,4.0,6.0,Negative,Neutral,66.0,40,No,No,Yes
4,941599210196,1.148634e+09,267,HR,0.59,0.41,96,73,115,23,218.0,215,69,42,74.0,20,10,4.0,6.0,Positive,Positive,47.0,38,No,Yes,Yes

In [6]:
train_df.shape

(5800, 27)

In [7]:
test_df.shape

(1200, 26)

In [8]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5800 entries, 0 to 5799
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Interview Id        5800 non-null   float64
 1   Candidate Id        5800 non-null   float64
 2   Interviewer Id      5800 non-null   int64
 3   Profile             5800 non-null   object
 4   S.L.R.C             5800 non-null   float64
 5   S.L.R.I             5800 non-null   float64
 6   A.T.T               5800 non-null   int64
 7   L.M.I               5800 non-null   int64
 8   L.M.C               5800 non-null   int64
 9   S.R                 5800 non-null   int64
 10  L.J.T.C             5800 non-null   int64
 11  L.J.T.I             5800 non-null   int64
 12  N.I.C               5800 non-null   int64
 13  N.I.I               5800 non-null   int64
 14  S.P.I               5800 non-null   int64
 15  S.P.C               5800 non-null   int64
 16  L.A.C               5800 non-null   int64
 17  L.A.I               5800 non-null   int64
 18  Q.A                 5800 non-null   int64
 19  P.E.I               5799 non-null   object
 20  P.E.C               5797 non-null   object
 21  COMPLIANCE Ratio    5800 non-null   int64
 22  Interview duration  5800 non-null   int64
 23  Interviewer Intro   5799 non-null   object
 24  Candidate into      5800 non-null   object
 25  Opp to ask          5799 non-null   object
 26  Status              5796 non-null   object
dtypes: float64(4), int64(16), object(7)
memory usage: 1.2+ MB

In [9]:
train_df['Candidate Id'].nunique()

5800

In [10]:
train_df['Interview Id'].nunique()

5800

In [11]:
train_df.describe(include='all')

,Interview Id,Candidate Id,Interviewer Id,Profile,S.L.R.C,S.L.R.I,A.T.T,L.M.I,L.M.C,S.R,L.J.T.C,L.J.T.I,N.I.C,N.I.I,S.P.I,S.P.C,L.A.C,L.A.I,Q.A,P.E.I,P.E.C,COMPLIANCE Ratio,Interview duration,Interviewer Intro,Candidate into,Opp to ask,Status
count,5.800000e+03,5.800000e+03,5800.000000,5800,5800.000000,5800.000000,5800.000000,5800.000000,5800.000000,5800.000000,5800.000000,5800.000000,5800.000000,5800.000000,5800.000000,5800.000000,5800.000000,5800.000000,5800.000000,5799,5797,5800.000000,5800.000000,5799,5800,5799,5796
unique,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,NaN,NaN,2,2,2,3
top,NaN,NaN,NaN,Developer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Negative,Neutral,NaN,NaN,No,No,Yes,Consider
freq,NaN,NaN,NaN,618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004,1971,NaN,NaN,2911,2936,2955,2311
mean,4.947029e+11,5.009458e+09,229.553448,NaN,0.748321,0.251679,69.927414,80.445172,80.084310,45.077414,150.231207,301.063103,37.709828,37.378448,55.175862,47.250690,8.019655,10.503621,4.507586,NaN,NaN,50.315517,37.306724,NaN,NaN,NaN,NaN
std,2.890097e+11,2.873886e+09,22.884836,NaN,0.144272,0.144272,29.464030,23.450059,23.540515,14.729066,87.265858,172.861851,19.042870,19.138247,20.373655,24.891818,4.311379,5.724640,1.690976,NaN,NaN,28.696299,13.298407,NaN,NaN,NaN,NaN
min,3.693968e+08,1.467066e+05,190.000000,NaN,0.500000,0.010000,20.000000,40.000000,40.000000,20.000000,0.000000,0.000000,5.000000,5.000000,20.000000,5.000000,1.000000,1.000000,2.000000,NaN,NaN,0.000000,15.000000,NaN,NaN,NaN,NaN
25%,2.423758e+11,2.513537e+09,210.000000,NaN,0.620000,0.130000,44.000000,60.000000,59.000000,32.000000,74.000000,153.000000,21.000000,21.000000,38.000000,26.000000,4.000000,6.000000,3.000000,NaN,NaN,25.000000,26.000000,NaN,NaN,NaN,NaN
50%,4.900364e+11,5.009811e+09,229.000000,NaN,0.750000,0.250000,70.000000,81.000000,81.000000,45.000000,150.000000,300.000000,38.000000,37.000000,55.000000,46.000000,8.000000,10.000000,5.000000,NaN,NaN,51.000000,37.000000,NaN,NaN,NaN,NaN
75%,7.456835e+11,7.468382e+09,250.000000,NaN,0.870000,0.380000,96.000000,101.000000,101.000000,58.000000,226.000000,451.000000,54.000000,54.000000,73.000000,69.000000,12.000000,15.000000,6.000000,NaN,NaN,75.000000,49.000000,NaN,NaN,NaN,NaN
max,9.999089e+11,9.999362e+09,268.000000,NaN,0.990000,0.500000,120.000000,120.000000,120.000000,70.000000,300.000000,600.000000,70.000000,70.000000,90.000000,90.000000,15.000000,20.000000,7.000000,NaN,NaN,100.000000,60.000000,NaN,NaN,NaN,NaN

In [12]:
train_df['Interviewer Id'].nunique()

79

In [13]:
train_df['Status'].nunique()

3

In [14]:
train_df['Status'].unique()

array(['Consider', 'May Consider', 'Not Consider', nan], dtype=object)

In [4]:
train_df.drop(['Interviewer Id','Candidate Id'],axis=1,inplace=True)
test_df.drop(['Interviewer Id','Candidate Id'],axis=1,inplace=True)

In [5]:
train_df.set_index('Interview Id',inplace=True)
test_df.set_index('Interview Id',inplace=True)

In [17]:
#train_df.set_index?

In [18]:
print(train_df.shape)
print(test_df.shape)

(5800, 24)
(1200, 23)

In [19]:
train_df.head()

,Profile,S.L.R.C,S.L.R.I,A.T.T,L.M.I,L.M.C,S.R,L.J.T.C,L.J.T.I,N.I.C,N.I.I,S.P.I,S.P.C,L.A.C,L.A.I,Q.A,P.E.I,P.E.C,COMPLIANCE Ratio,Interview duration,Interviewer Intro,Candidate into,Opp to ask,Status
Interview Id,,,,,,,,,,,,,,,,,,,,,,,,
6.913030e+11,Developer,0.98,0.02,53,88,93,32,88,106,41,66,42,47,13,15,6,Neutral,Neutral,98,37,No,Yes,Yes,Consider
9.214326e+11,Sales,0.67,0.33,51,53,44,36,93,313,28,62,32,52,5,15,4,Neutral,Negative,54,33,No,No,Yes,Consider
4.718839e+10,Program Manager,0.81,0.19,60,77,75,54,52,67,26,14,57,34,4,7,3,Positive,Positive,31,58,No,Yes,No,Consider
9.943741e+11,Marketing,0.69,0.31,93,42,103,49,115,166,62,55,65,75,10,10,7,Positive,Negative,24,35,No,Yes,No,Consider
3.509007e+11,QA Automation,0.57,0.43,44,44,119,66,190,394,7,32,36,74,13,7,3,Negative,Positive,73,60,Yes,Yes,No,Consider

In [20]:
test_df.head()

,Profile,S.L.R.C,S.L.R.I,A.T.T,L.M.I,L.M.C,S.R,L.J.T.C,L.J.T.I,N.I.C,N.I.I,S.P.I,S.P.C,L.A.C,L.A.I,Q.A,P.E.I,P.E.C,COMPLIANCE Ratio,Interview duration,Interviewer Intro,Candidate into,Opp to ask
Interview Id,,,,,,,,,,,,,,,,,,,,,,,
702127796635,Product Manager,0.52,0.48,103,53,77,30,26.0,287,8,22,69.0,88,5,19.0,4.0,Positive,Negative,24.0,49,Yes,Yes,Yes
613490569071,Product Manager,0.87,0.13,54,57,57,68,179.0,253,62,40,47.0,81,1,9.0,7.0,Positive,Neutral,99.0,24,No,Yes,Yes
759998772623,QA Automation,0.60,0.40,50,117,93,36,137.0,31,40,52,57.0,13,7,15.0,3.0,Negative,Positive,16.0,16,Yes,No,Yes
391760082113,HR,0.52,0.48,102,114,66,31,176.0,242,69,66,59.0,10,10,4.0,6.0,Negative,Neutral,66.0,40,No,No,Yes
941599210196,HR,0.59,0.41,96,73,115,23,218.0,215,69,42,74.0,20,10,4.0,6.0,Positive,Positive,47.0,38,No,Yes,Yes

In [21]:
train_df.isnull().sum()

Profile               0
S.L.R.C               0
S.L.R.I               0
A.T.T                 0
L.M.I                 0
L.M.C                 0
S.R                   0
L.J.T.C               0
L.J.T.I               0
N.I.C                 0
N.I.I                 0
S.P.I                 0
S.P.C                 0
L.A.C                 0
L.A.I                 0
Q.A                   0
P.E.I                 1
P.E.C                 3
COMPLIANCE Ratio      0
Interview duration    0
Interviewer Intro     1
Candidate into        0
Opp to ask            1
Status                4
dtype: int64

In [6]:
train_df.dropna(subset=['P.E.I','P.E.C','Interviewer Intro','Opp to ask','Status'],axis=0,inplace=True)

In [23]:
train_df.isnull().sum()

Profile               0
S.L.R.C               0
S.L.R.I               0
A.T.T                 0
L.M.I                 0
L.M.C                 0
S.R                   0
L.J.T.C               0
L.J.T.I               0
N.I.C                 0
N.I.I                 0
S.P.I                 0
S.P.C                 0
L.A.C                 0
L.A.I                 0
Q.A                   0
P.E.I                 0
P.E.C                 0
COMPLIANCE Ratio      0
Interview duration    0
Interviewer Intro     0
Candidate into        0
Opp to ask            0
Status                0
dtype: int64

In [24]:
test_df.isnull().sum()

Profile               0
S.L.R.C               0
S.L.R.I               1
A.T.T                 0
L.M.I                 0
L.M.C                 0
S.R                   0
L.J.T.C               1
L.J.T.I               0
N.I.C                 0
N.I.I                 0
S.P.I                 2
S.P.C                 0
L.A.C                 0
L.A.I                 1
Q.A                   1
P.E.I                 2
P.E.C                 2
COMPLIANCE Ratio      1
Interview duration    0
Interviewer Intro     2
Candidate into        0
Opp to ask            0
dtype: int64

In [7]:
test_df.dropna(subset=['P.E.I','P.E.C','Interviewer Intro','COMPLIANCE Ratio','Q.A','L.A.I','S.P.I','L.J.T.C','S.L.R.I'],axis=0,inplace=True)

In [26]:
test_df.isnull().sum()

Profile               0
S.L.R.C               0
S.L.R.I               0
A.T.T                 0
L.M.I                 0
L.M.C                 0
S.R                   0
L.J.T.C               0
L.J.T.I               0
N.I.C                 0
N.I.I                 0
S.P.I                 0
S.P.C                 0
L.A.C                 0
L.A.I                 0
Q.A                   0
P.E.I                 0
P.E.C                 0
COMPLIANCE Ratio      0
Interview duration    0
Interviewer Intro     0
Candidate into        0
Opp to ask            0
dtype: int64

In [27]:
train_df.duplicated().sum()

0

In [28]:
test_df.duplicated().sum()

0

In [29]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5790 entries, 691302971928.0 to 863040675358.0
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Profile             5790 non-null   object
 1   S.L.R.C             5790 non-null   float64
 2   S.L.R.I             5790 non-null   float64
 3   A.T.T               5790 non-null   int64
 4   L.M.I               5790 non-null   int64
 5   L.M.C               5790 non-null   int64
 6   S.R                 5790 non-null   int64
 7   L.J.T.C             5790 non-null   int64
 8   L.J.T.I             5790 non-null   int64
 9   N.I.C               5790 non-null   int64
 10  N.I.I               5790 non-null   int64
 11  S.P.I               5790 non-null   int64
 12  S.P.C               5790 non-null   int64
 13  L.A.C               5790 non-null   int64
 14  L.A.I               5790 non-null   int64
 15  Q.A                 5790 non-null   int64
 16  P.E.I               5790 non-null   object
 17  P.E.C               5790 non-null   object
 18  COMPLIANCE Ratio    5790 non-null   int64
 19  Interview duration  5790 non-null   int64
 20  Interviewer Intro   5790 non-null   object
 21  Candidate into      5790 non-null   object
 22  Opp to ask          5790 non-null   object
 23  Status              5790 non-null   object
dtypes: float64(2), int64(15), object(7)
memory usage: 1.1+ MB

In [30]:
train_df.describe(include='all')

,Profile,S.L.R.C,S.L.R.I,A.T.T,L.M.I,L.M.C,S.R,L.J.T.C,L.J.T.I,N.I.C,N.I.I,S.P.I,S.P.C,L.A.C,L.A.I,Q.A,P.E.I,P.E.C,COMPLIANCE Ratio,Interview duration,Interviewer Intro,Candidate into,Opp to ask,Status
count,5790,5790.000000,5790.000000,5790.000000,5790.000000,5790.000000,5790.000000,5790.000000,5790.000000,5790.000000,5790.000000,5790.000000,5790.000000,5790.000000,5790.000000,5790.000000,5790,5790,5790.000000,5790.000000,5790,5790,5790,5790
unique,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,NaN,NaN,2,2,2,3
top,Developer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Negative,Neutral,NaN,NaN,No,No,Yes,Consider
freq,618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999,1968,NaN,NaN,2907,2932,2953,2309
mean,NaN,0.748268,0.251732,69.946805,80.451641,80.082383,45.079275,150.267876,300.969948,37.710017,37.373402,55.178584,47.265803,8.018653,10.501900,4.507081,NaN,NaN,50.337651,37.307427,NaN,NaN,NaN,NaN
std,NaN,0.144249,0.144249,29.465837,23.451585,23.544798,14.735396,87.272489,172.904739,19.048039,19.135869,20.379943,24.898557,4.309899,5.725805,1.691290,NaN,NaN,28.699222,13.298042,NaN,NaN,NaN,NaN
min,NaN,0.500000,0.010000,20.000000,40.000000,40.000000,20.000000,0.000000,0.000000,5.000000,5.000000,20.000000,5.000000,1.000000,1.000000,2.000000,NaN,NaN,0.000000,15.000000,NaN,NaN,NaN,NaN
25%,NaN,0.620000,0.130000,44.000000,60.000000,59.250000,32.000000,74.000000,153.000000,21.000000,21.000000,38.000000,26.000000,4.000000,6.000000,3.000000,NaN,NaN,25.000000,26.000000,NaN,NaN,NaN,NaN
50%,NaN,0.750000,0.250000,70.000000,81.000000,81.000000,45.000000,150.000000,300.000000,38.000000,37.000000,55.000000,46.000000,8.000000,10.000000,5.000000,NaN,NaN,51.000000,37.000000,NaN,NaN,NaN,NaN
75%,NaN,0.870000,0.380000,96.000000,101.000000,101.000000,58.000000,226.000000,451.000000,54.000000,54.000000,73.000000,69.000000,12.000000,15.000000,6.000000,NaN,NaN,75.000000,49.000000,NaN,NaN,NaN,NaN
max,NaN,0.990000,0.500000,120.000000,120.000000,120.000000,70.000000,300.000000,600.000000,70.000000,70.000000,90.000000,90.000000,15.000000,20.000000,7.000000,NaN,NaN,100.000000,60.000000,NaN,NaN,NaN,NaN

In [31]:
test_df.describe(include='all')

,Profile,S.L.R.C,S.L.R.I,A.T.T,L.M.I,L.M.C,S.R,L.J.T.C,L.J.T.I,N.I.C,N.I.I,S.P.I,S.P.C,L.A.C,L.A.I,Q.A,P.E.I,P.E.C,COMPLIANCE Ratio,Interview duration,Interviewer Intro,Candidate into,Opp to ask
count,1187,1187.000000,1187.000000,1187.000000,1187.000000,1187.000000,1187.000000,1187.000000,1187.000000,1187.000000,1187.000000,1187.000000,1187.000000,1187.000000,1187.000000,1187.000000,1187,1187,1187.000000,1187.000000,1187,1187,1187
unique,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,NaN,NaN,2,2,2
top,Account Manager,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Negative,Positive,NaN,NaN,No,Yes,No
freq,132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,405,409,NaN,NaN,594,606,595
mean,NaN,0.737826,0.262174,70.153328,79.538332,81.410278,45.055602,151.598147,305.304971,37.466723,37.668071,54.754844,47.972199,7.823926,10.716933,4.366470,NaN,NaN,50.144061,37.743892,NaN,NaN,NaN
std,NaN,0.144447,0.144447,29.117545,23.098130,23.103207,14.591351,86.869275,175.610301,18.955469,19.190121,20.659442,24.345152,4.406247,5.730079,1.687566,NaN,NaN,29.360072,13.382495,NaN,NaN,NaN
min,NaN,0.500000,0.010000,20.000000,40.000000,40.000000,20.000000,0.000000,0.000000,5.000000,5.000000,20.000000,5.000000,1.000000,1.000000,2.000000,NaN,NaN,0.000000,15.000000,NaN,NaN,NaN
25%,NaN,0.610000,0.140000,44.500000,59.000000,62.000000,32.000000,79.000000,151.500000,21.000000,20.000000,37.000000,28.000000,4.000000,6.000000,3.000000,NaN,NaN,23.000000,26.000000,NaN,NaN,NaN
50%,NaN,0.740000,0.260000,71.000000,79.000000,81.000000,45.000000,151.000000,306.000000,37.000000,38.000000,55.000000,48.000000,8.000000,11.000000,4.000000,NaN,NaN,50.000000,38.000000,NaN,NaN,NaN
75%,NaN,0.860000,0.390000,96.000000,99.500000,102.000000,57.500000,228.000000,457.500000,54.000000,54.000000,73.000000,69.000000,12.000000,16.000000,6.000000,NaN,NaN,76.000000,50.000000,NaN,NaN,NaN
max,NaN,0.990000,0.500000,120.000000,120.000000,120.000000,70.000000,300.000000,599.000000,70.000000,70.000000,90.000000,90.000000,15.000000,20.000000,7.000000,NaN,NaN,100.000000,60.000000,NaN,NaN,NaN

In [32]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1187 entries, 702127796635 to 480519602140
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Profile             1187 non-null   object
 1   S.L.R.C             1187 non-null   float64
 2   S.L.R.I             1187 non-null   float64
 3   A.T.T               1187 non-null   int64
 4   L.M.I               1187 non-null   int64
 5   L.M.C               1187 non-null   int64
 6   S.R                 1187 non-null   int64
 7   L.J.T.C             1187 non-null   float64
 8   L.J.T.I             1187 non-null   int64
 9   N.I.C               1187 non-null   int64
 10  N.I.I               1187 non-null   int64
 11  S.P.I               1187 non-null   float64
 12  S.P.C               1187 non-null   int64
 13  L.A.C               1187 non-null   int64
 14  L.A.I               1187 non-null   float64
 15  Q.A                 1187 non-null   float64
 16  P.E.I               1187 non-null   object
 17  P.E.C               1187 non-null   object
 18  COMPLIANCE Ratio    1187 non-null   float64
 19  Interview duration  1187 non-null   int64
 20  Interviewer Intro   1187 non-null   object
 21  Candidate into      1187 non-null   object
 22  Opp to ask          1187 non-null   object
dtypes: float64(7), int64(10), object(6)
memory usage: 222.6+ KB

In [33]:
for i in train_df.columns:
    print({i:train_df[i].unique()})

{'Profile': array(['Developer', 'Sales', 'Program Manager', 'Marketing',
       'QA Automation', 'Account Manager', 'Data Scientist',
       'Product Manager', 'QA Manual', 'HR'], dtype=object)}
{'S.L.R.C': array([0.98, 0.67, 0.81, 0.69, 0.57, 0.65, 0.52, 0.91, 0.72, 0.82, 0.66,
       0.51, 0.54, 0.55, 0.5 , 0.79, 0.83, 0.73, 0.63, 0.62, 0.88, 0.8 ,
       0.99, 0.68, 0.85, 0.84, 0.7 , 0.93, 0.87, 0.94, 0.71, 0.58, 0.77,
       0.96, 0.76, 0.61, 0.53, 0.59, 0.75, 0.92, 0.64, 0.97, 0.95, 0.56,
       0.89, 0.86, 0.6 , 0.78, 0.74, 0.9 ])}
{'S.L.R.I': array([0.02, 0.33, 0.19, 0.31, 0.43, 0.35, 0.48, 0.09, 0.28, 0.18, 0.34,
       0.49, 0.46, 0.45, 0.5 , 0.21, 0.17, 0.27, 0.37, 0.38, 0.12, 0.2 ,
       0.01, 0.32, 0.15, 0.16, 0.3 , 0.07, 0.13, 0.06, 0.29, 0.42, 0.23,
       0.04, 0.24, 0.39, 0.47, 0.41, 0.25, 0.08, 0.36, 0.03, 0.05, 0.44,
       0.11, 0.14, 0.4 , 0.22, 0.26, 0.1 ])}
{'A.T.T': array([ 53,  51,  60,  93,  44,  75,  49,  66,  36,  27,  24, 116,  50,
        85,  78,  62,  95, 114,  35,  55,  72,  92,  69, 115,  68,  73,
        70,  26,  45,  65,  21,  99,  47, 118,  86, 113,  29,  63,  83,
        81,  80, 101, 109,  52,  30,  87,  37,  91,  61,  46, 110, 120,
        89,  67,  48,  39, 104,  79, 108,  96,  34, 105,  41, 117,  88,
        38, 103,  20,  74,  90,  25,  82,  94,  59, 119,  22, 112,  77,
       100, 107,  57,  40, 102,  98, 111,  43,  76,  32,  97,  31,  64,
        71,  84, 106,  28,  56,  42,  33,  54,  58,  23], dtype=int64)}
{'L.M.I': array([ 88,  53,  77,  42,  44,  72,  59, 113,  82,  74,  51,  40, 116,
        84,  61, 109, 107,  96,  83, 120, 101, 110,  98,  80,  68, 103,
        95,  91,  64,  66,  89, 100,  46,  75, 104,  92,  99,  87,  50,
        60,  69,  93,  57,  70,  52, 119, 117,  94,  86,  56,  85, 115,
       105, 112, 114,  54,  48,  47,  79,  62,  63,  45,  90,  73,  41,
       118,  43,  71,  67,  58,  55,  49, 108,  78, 102,  97,  65,  76,
       111,  81, 106], dtype=int64)}
{'L.M.C': array([ 93,  44,  75, 103, 119,  95,  99, 117,  51, 108,  83, 110,  90,
       120, 109,  85, 105,  94,  55,  79,  46,  53,  65, 100,  73,  56,
        78,  61, 106,  88,  54,  60,  58,  84,  52,  59, 111,  48,  41,
       113, 114,  70,  97, 104, 116,  64,  62, 102, 118,  69,  74,  71,
        76,  91,  86,  45,  77,  47,  82,  49,  66,  42,  80,  98,  89,
        63,  43,  67,  68,  40,  72,  81,  96, 112,  87, 107,  50, 101,
        92, 115,  57], dtype=int64)}
{'S.R': array([32, 36, 54, 49, 66, 59, 27, 34, 63, 60, 57, 48, 44, 52, 23, 43, 24,
       40, 47, 31, 20, 28, 39, 25, 35, 50, 45, 67, 58, 46, 65, 62, 61, 30,
       41, 38, 26, 68, 53, 37, 42, 51, 70, 55, 22, 64, 33, 56, 21, 69, 29],
      dtype=int64)}
{'L.J.T.C': array([ 88,  93,  52, 115, 190, 159, 156,  37,  87,  45, 191,  84,  65,
         6, 220, 279,  78, 224, 273, 152, 214, 140,   5, 103,  10,  48,
       247, 175, 296, 292, 281, 113, 196,  11,  95, 253, 171, 123, 142,
       233,  24, 226,  51,  47, 120,  55,   1, 104,  29,  12, 244, 289,
        69,  80, 225,   9, 150, 112,  46,  82, 218,  25,  54, 264,   0,
       232, 250, 251, 161, 282, 180, 284, 299, 293,  58, 211,  57, 187,
       203, 174, 213, 285, 111, 125, 134,  70, 170, 145,  40, 158, 106,
       283, 185,  89,  13,  81, 263, 249, 246,  68, 130, 166,  39,  50,
       274, 154, 114,  62, 101,  28,  16, 217, 127, 131, 234, 265,  34,
       243, 286,  23, 277,  31,  30, 176, 294,  98, 260, 256, 295, 143,
        53, 168, 219,   7, 182, 122,  19,  66, 189, 164,  77, 229, 206,
       204, 212, 173, 178,  85, 149,  79,   4, 117, 162, 268, 108, 148,
       105,  15,  14, 200, 227, 257,  27, 121, 151,  18, 128, 116, 135,
       110, 280,  21, 216, 167,  20, 261, 141,  91,  36,  38, 221, 119,
       181, 205, 245, 124, 239,  64, 129, 184, 270, 195,  43,  76, 223,
       107, 186, 290, 291,  49,  44, 241,  60, 198, 215, 201,  56, 259,
        33, 102, 267, 266, 235,  74, 126, 207,   2, 298, 262,  17, 236,
       137, 163, 228,  26,  97,  99,  22, 183,   8, 272, 177, 194, 144,
        72, 248, 199, 153, 238,  63, 139, 278, 210, 252,  94, 271, 118,
       193,  90, 288,  67,  75, 133, 254, 209,  73, 255,  59, 172,  32,
        71, 192,  92,   3, 276, 240,  96, 136, 275, 132, 179,  61, 287,
       258, 138, 188,  41, 165, 147, 300,  83, 222,  42, 230, 242, 202,
       197,  86, 269, 297, 208, 157, 169, 160, 146, 109, 155,  35, 231,
       100, 237], dtype=int64)}
{'L.J.T.I': array([106, 313,  67, 166, 394, 241, 288, 208,  86, 218, 126, 331, 102,
       170, 133, 274,  25, 250,  88, 315,  84, 242,  70, 383,  38, 291,
       537, 339, 231,  55, 439, 476, 406, 546, 116, 298, 270, 374, 299,
        22, 500, 151,   1, 360, 446, 148, 167, 395,  23, 452,  95, 239,
        66, 152, 386,  17, 487, 128, 568, 171, 542,  14, 294, 351, 502,
       410, 382, 305, 595, 139, 598, 597, 181, 536, 548, 317, 180, 338,
       237, 435,  98, 266, 248, 306, 142, 103, 214,   3, 177, 554, 510,
        48, 419, 418,  47, 283, 268, 599, 324, 349,  60, 560, 463, 201,
        97, 207,  24, 491, 182, 505, 400, 379, 457, 361,  40, 368, 569,
       215, 220, 424, 458, 260, 221, 564, 194, 329, 496, 404, 583,  87,
       205, 118, 276,  78, 192, 516, 263, 385, 236, 240, 539,  37, 145,
       380, 497,  54,  11, 488, 254, 573, 474,  49, 252, 579, 187,  69,
         4, 190, 387, 176, 225, 586, 193, 362, 512, 555, 592, 267, 256,
       259, 440,   2, 273,  91, 581, 111, 333, 414, 393,  61, 113, 161,
       334, 543, 327,   6, 594, 169,  31, 332, 483, 304, 210, 427, 480,
       137, 532, 322, 538, 149, 162, 375, 159, 163,  74, 486, 415, 528,
       443,   0, 279, 588, 154, 371, 357, 513, 584, 524, 455, 567, 341,
       388, 467, 578, 453, 296, 292, 129, 325, 143,  99, 484, 196, 562,
       489,  92, 384, 376,  33, 125, 350, 582, 572, 450, 308,  39, 140,
       544, 280, 153,  71, 156, 511, 314, 150, 203,  42, 454,  43, 121,
        35, 523, 465, 251, 466, 441, 470, 392, 566,  18,  51, 226, 110,
        10, 580, 434,  89,  44, 456, 183, 356, 461, 168, 425, 442, 493,
       422, 204, 563, 249, 264, 165, 477, 529, 200, 409, 319, 363, 195,
        41, 108, 590, 591, 230, 481,  82, 574, 570, 269, 433, 556, 553,
       206,  34, 550, 365, 179, 459, 286,  50, 188, 460, 232,  93, 191,
       600,  12,  64, 405, 321, 147, 585, 130, 234, 115,  81, 506, 401,
       100, 185,  21, 144, 109,  85, 377, 233, 337, 344, 504, 381, 558,
       571, 390, 123, 557,  26,   8, 416, 535, 235, 451, 175, 199, 408,
         5,  75, 508, 222,  94,  32,  76, 445, 391, 520, 397, 303,  27,
       307, 172, 275, 449, 287,   9, 509,  20, 164,  13, 411, 212, 531,
       596,  96, 447, 289, 312, 514, 310, 160, 369, 290, 372, 323, 430,
       343, 244, 436,  30,  45, 403, 155, 271, 347, 211, 309,  63,  68,
       261, 499,  72,  16, 507, 265, 189, 104,  90, 525, 471,  36, 482,
       478, 396, 178, 114, 138, 217, 423, 101, 366, 438, 122, 216, 561,
       282, 224, 345, 407, 444,  52, 472, 420, 389, 534, 120, 330, 541,
       545, 262, 373,  46, 485, 473, 517, 301,  59, 258, 342, 132,  79,
       468, 364, 335, 413, 495,   7, 501,  28, 336, 186, 530, 253,  73,
       518, 328, 540, 398,  56, 277, 247, 417, 348, 136, 243, 173, 157,
       464, 412, 229, 429, 367, 219, 284, 174, 519,  15, 492, 431, 378,
       355,  62, 295, 257, 490, 547, 503, 124, 255, 577, 462, 352, 302,
       432, 359,  65, 533, 521, 112, 475, 479, 515, 184, 549, 131, 119,
       134, 494, 238,  57,  77, 575, 576,  29, 213, 498, 426, 527, 551,
       522,  19, 245, 297, 316, 552, 340, 135,  80, 402, 353, 354, 107,
        83, 272, 227, 399, 285, 300, 197, 593, 370, 428, 141, 559, 318,
       278, 358, 469, 202, 146, 127, 281, 326, 346, 198, 105,  58, 421,
        53, 589, 565, 320, 526, 437, 311, 448, 228, 223, 209, 587, 246,
       117, 293, 158], dtype=int64)}
{'N.I.C': array([41, 28, 26, 62,  7, 31, 14,  6, 29, 12, 18, 50, 63, 23, 53, 49, 68,
       17, 67, 54, 35, 19, 21, 51, 46, 10, 37, 43, 64, 58, 16, 40, 15, 61,
        8, 42, 59, 36, 45, 44,  9, 47, 34, 20, 48, 32, 11, 69, 56, 66, 38,
       13, 39, 52, 27, 24, 30,  5, 55, 60, 65, 70, 22, 25, 57, 33],
      dtype=int64)}
{'N.I.I': array([66, 62, 14, 55, 32, 52,  7, 44, 69, 60, 59, 27, 67, 35, 65, 21, 13,
       10, 63, 34, 58,  8, 70, 11, 24, 37,  9, 51, 38, 50, 36, 45, 43, 42,
       26, 54, 19, 30, 15, 46,  6, 39,  5, 22, 18, 41, 29, 23, 64, 25, 68,
       20, 56, 16, 48, 49, 57, 47, 61, 33, 12, 28, 31, 17, 53, 40],
      dtype=int64)}
{'S.P.I': array([42, 32, 57, 65, 36, 33, 76, 61, 60, 50, 81, 88, 22, 49, 85, 63, 58,
       77, 75, 45, 86, 62, 20, 56, 87, 83, 48, 84, 40, 27, 46, 59, 26, 30,
       90, 54, 51, 79, 21, 41, 31, 72, 25, 89, 29, 38, 71, 55, 52, 68, 70,
       47, 80, 28, 53, 23, 43, 74, 69, 39, 66, 24, 35, 73, 67, 82, 64, 78,
       37, 34, 44], dtype=int64)}
{'S.P.C': array([47, 52, 34, 75, 74,  9, 45, 35, 60, 64, 15, 58, 70,  8, 90, 10, 57,
       25, 22, 50, 41, 44, 85, 43, 46, 88, 36, 56,  6, 31, 26, 83, 28, 79,
       13, 61, 49, 42, 24, 16, 39, 27, 29, 51, 19, 72, 40, 67, 66, 68, 55,
       30, 11, 14, 62, 63,  5, 82, 23, 37, 84, 32, 89, 80, 48, 17, 78, 20,
       12, 76, 86, 18, 65, 77,  7, 53, 87, 33, 21, 69, 71, 38, 54, 59, 73,
       81], dtype=int64)}
{'L.A.C': array([13,  5,  4, 10, 11,  1,  6,  2,  9, 15, 12,  7,  8, 14,  3],
      dtype=int64)}
{'L.A.I': array([15,  7, 10, 13,  3,  6, 19,  4, 17,  1, 14, 18,  2, 20,  9, 12, 16,
       11,  8,  5], dtype=int64)}
{'Q.A': array([6, 4, 3, 7, 5, 2], dtype=int64)}
{'P.E.I': array(['Neutral', 'Positive', 'Negative'], dtype=object)}
{'P.E.C': array(['Neutral', 'Negative', 'Positive'], dtype=object)}
{'COMPLIANCE Ratio': array([ 98,  54,  31,  24,  73,  41,  32,  74,  70,  86,  44,  27,  33,
        56,  84,  12,  20,  53,  79,  23,  49,  18,  75,  82,  36,   7,
        66,  51,  69,  95,  60,  35,  93,  37,  57,   8,  50,  38, 100,
        99,  58,  87,  89,  77,  22,  11,  13,  34,  55,  26,  64,  72,
        94,  16,  30,  10,  68,  67,  47,  65,  59,  63,  97,   2,  14,
        61,  21,   4,  48,  71,  43,   1,  28,  40,  92,  39,  19,  91,
        46,  17,  96,   9,  29,  45,   6,  80,  42,   3,   0,  90,  76,
        85,  15,  78,  25,  81,   5,  52,  88,  83,  62], dtype=int64)}
{'Interview duration': array([37, 33, 58, 35, 60, 44, 48, 43, 38, 22, 51, 28, 36, 59, 31, 24, 32,
       41, 20, 55, 54, 15, 46, 29, 26, 17, 34, 57, 53, 52, 30, 18, 42, 49,
       40, 19, 45, 56, 16, 47, 21, 27, 39, 23, 25, 50], dtype=int64)}
{'Interviewer Intro': array(['No', 'Yes'], dtype=object)}
{'Candidate into': array(['Yes', 'No'], dtype=object)}
{'Opp to ask': array(['Yes', 'No'], dtype=object)}
{'Status': array(['Consider', 'May Consider', 'Not Consider'], dtype=object)}

In [34]:
for i in test_df.columns:
    print({i:test_df[i].unique()})

{'Profile': array(['Product Manager', 'QA Automation', 'HR', 'Developer',
       'Account Manager', 'Program Manager', 'Sales', 'Data Scientist',
       'QA Manual', 'Marketing'], dtype=object)}
{'S.L.R.C': array([0.52, 0.87, 0.6 , 0.59, 0.88, 0.81, 0.99, 0.67, 0.58, 0.78, 0.68,
       0.85, 0.9 , 0.84, 0.93, 0.77, 0.69, 0.57, 0.98, 0.54, 0.53, 0.75,
       0.79, 0.74, 0.86, 0.71, 0.82, 0.55, 0.65, 0.56, 0.95, 0.61, 0.62,
       0.72, 0.66, 0.7 , 0.64, 0.96, 0.51, 0.73, 0.76, 0.97, 0.8 , 0.92,
       0.5 , 0.63, 0.94, 0.83, 0.91, 0.89])}
{'S.L.R.I': array([0.48, 0.13, 0.4 , 0.41, 0.12, 0.19, 0.01, 0.33, 0.42, 0.22, 0.32,
       0.15, 0.1 , 0.16, 0.07, 0.23, 0.31, 0.43, 0.02, 0.46, 0.47, 0.25,
       0.21, 0.26, 0.14, 0.29, 0.18, 0.45, 0.35, 0.44, 0.05, 0.39, 0.38,
       0.28, 0.34, 0.3 , 0.36, 0.04, 0.49, 0.27, 0.24, 0.03, 0.2 , 0.08,
       0.5 , 0.37, 0.06, 0.17, 0.09, 0.11])}
{'A.T.T': array([103,  54,  50, 102,  96,  23,  52,  67,  35,  49, 100,  29,  77,
        56,  85,  95, 110,  73,  28,  74, 119,  24,  57,  93, 113,  45,
        38,  51,  84,  60,  86,  72,  83,  92,  65, 106,  99,  75,  20,
        22,  40,  90,  97,  88,  71,  33, 105, 101,  66,  25,  78,  37,
        47,  62,  98, 116,  82,  34,  58,  42,  59,  31,  70, 111,  79,
       114,  55,  61,  39, 108,  43,  64,  44,  87,  63, 115,  46,  41,
        32, 120,  36,  30,  81, 118, 109,  53,  91, 107,  76,  80,  94,
        68, 112,  21,  27,  26, 104,  89, 117,  48,  69], dtype=int64)}
{'L.M.I': array([ 53,  57, 117, 114,  73,  87,  85, 108,  88, 113,  79,  63, 101,
        60, 102,  84,  80,  70,  75,  47,  82,  71,  96,  59,  42, 116,
        89,  76,  72,  86,  45,  92,  91, 118,  58,  48,  51,  64,  95,
        77,  74,  90, 100,  56,  97,  66,  83,  52, 120,  43,  46,  49,
       111,  99, 106, 112,  81,  98, 103,  55,  62,  65, 109,  50, 119,
        69, 110,  41,  67,  68,  93, 105,  40,  61, 115, 104,  78, 107,
        54,  94,  44], dtype=int64)}
{'L.M.C': array([ 77,  57,  93,  66, 115,  46,  53,  79,  64,  94,  48,  58, 106,
        68,  51,  89,  83, 114, 111,  47, 112,  81,  86,  56, 113, 100,
       116,  42,  82, 119,  55,  75,  54,  60,  72, 101,  73, 120,  91,
        96,  49,  44, 105,  71,  65, 102, 107, 104,  87, 103,  62,  85,
       110,  45,  63,  70,  76,  74,  84,  99,  43,  40,  88,  98,  95,
        92,  78,  52,  80,  50, 118, 108,  67, 109,  90,  69, 117,  97,
        41,  61,  59], dtype=int64)}
{'S.R': array([30, 68, 36, 31, 23, 59, 66, 33, 49, 32, 55, 43, 37, 52, 60, 54, 42,
       34, 21, 57, 62, 70, 46, 40, 29, 58, 20, 63, 27, 22, 65, 38, 41, 48,
       26, 51, 69, 53, 45, 35, 56, 61, 64, 50, 25, 44, 39, 47, 28, 24, 67],
      dtype=int64)}
{'L.J.T.C': array([ 26., 179., 137., 176., 218., 246., 286., 108., 168.,  37., 265.,
        74., 133., 226.,  88.,  79., 134.,  77.,  19.,  63., 252.,  47.,
        51.,  13., 219.,   1., 150.,  49.,  53., 225., 243., 128.,  87.,
       239., 132., 162., 120., 143., 178.,  73.,  84., 267.,  16., 277.,
         9.,  83., 264., 111., 298., 171., 292.,  18., 141.,  76., 154.,
        10., 173.,  32.,  45., 200., 195., 268., 235.,   0.,  65.,  43.,
       293., 114., 284.,  38., 212., 291.,  85., 136.,   4., 149., 214.,
       152., 166., 216., 101., 255.,  66., 233., 289., 180., 263., 257.,
       241.,  41.,  70.,  29., 145.,   2.,  78., 269., 174., 274., 160.,
       282., 129.,  95., 142., 183., 290.,  67.,  81.,   8., 209.,  20.,
       155., 131., 185., 295.,  97., 251.,  75., 231., 118., 197., 285.,
       288.,  40., 170., 105., 184., 110., 232., 175.,  14.,  36., 205.,
       260., 238.,  59., 138., 127., 115., 217., 278., 193., 221., 250.,
       196.,  35.,  12., 106.,  71., 213.,  60.,  86., 215.,  11., 126.,
       113., 169., 192., 296., 223.,  69.,  28.,  62., 272.,  58.,  96.,
       230., 283.,  98., 121., 280., 194., 159.,  25., 146.,  90., 177.,
       109., 158., 163.,  72.,  52., 224., 165., 102., 144., 256.,  31.,
       249., 188., 135., 112., 122., 242.,   5.,  54., 271.,  82., 198.,
       237.,  94., 161., 247., 199., 119., 187., 172.,  50.,  42., 156.,
       117., 294., 259., 201., 116., 300., 186.,  61.,  44.,  15., 270.,
        56., 182., 275.,  57., 164.,  80.,  92., 220., 151., 229., 147.,
        30.,   7., 262., 167., 153.,  91., 281.,  68., 236., 261.,  21.,
        93., 299., 190., 123., 266., 227.,  55., 181., 100., 157., 204.,
       140., 189., 244., 297., 258.,   3.,  89.,  24., 103., 104., 130.,
       273., 208., 206.,   6.,  46., 228.,  23., 287., 203.,  33., 240.,
       211., 245.,  39.,  17., 139., 148., 248., 253.,  22., 276., 234.,
       222.,  48., 107., 207., 125.,  99., 254., 124.])}
{'L.J.T.I': array([287, 253,  31, 242, 215, 518,  90, 562, 410, 182, 286, 383, 363,
       206, 447, 589,  81, 186, 342, 596, 399, 540, 115, 433, 267, 402,
       157, 370, 441, 344, 381, 336, 574, 382, 101, 294, 311,  60, 223,
       482, 519, 241, 113, 103, 208, 428, 119, 567, 495, 369, 125, 405,
       124, 372, 452, 569, 198,  13, 549, 505, 530, 526, 458, 579, 218,
       486, 347, 161, 497, 148, 104, 221, 457, 348, 290, 479, 222, 177,
        27, 272, 599, 131, 362, 153,  66,  89, 456,  22, 385, 498, 575,
       577, 459, 460, 199, 593, 543,  53, 564, 116,  76, 143, 487, 412,
       407, 393,  26, 225, 233, 591,  55, 175, 100, 517, 319,  59, 523,
        93, 389, 276, 334, 595, 355, 118, 325, 368, 578, 130, 553,  43,
       304, 340,   5, 411, 468, 168, 491, 173, 582, 436, 137, 451, 117,
       255,  44, 413, 514, 248, 262, 496, 291, 404, 350, 330, 134, 252,
       246,  70, 546, 141, 333, 335, 269, 282, 538, 273, 151, 114, 424,
       298, 187, 365, 236, 318, 289, 156, 563, 227, 416,  12, 108, 597,
        41, 326, 485, 503, 375,   7, 214,  85, 516, 317,  45, 371, 510,
       360, 149, 293, 555, 469,  30, 533, 226, 261, 374,  37, 367, 440,
       257,  86, 576, 426, 448, 268, 106,  52, 529,  36, 509,  77, 557,
       245,  82, 583, 454, 331, 490,  46, 420, 419, 572, 159, 281, 285,
       321, 558,  51, 548, 284, 180, 395, 504,  38, 588, 453, 183, 481,
       190, 197, 179,   4, 401,  18, 205, 561, 201, 132, 107, 138, 531,
       128, 217, 354,   3, 435, 327, 566, 309, 135, 580, 162, 539, 465,
       200, 184, 542, 211, 278, 373,  97,  58,  79, 473, 346, 171, 239,
        23, 429, 476, 154, 102, 264, 288, 488,  25, 204, 307, 229, 237,
       357, 379, 524, 592, 391, 527, 415, 455,  42, 534,  71, 235, 256,
        57, 390, 377, 142, 343,  33, 220, 438,  50, 250, 432, 295, 594,
       109, 366, 270, 176, 423, 260, 322, 445, 181, 120,  92,   9, 450,
       525, 111,  21, 292, 274, 408, 483, 240,   8, 584,  72, 356, 442,
       573,  94, 277, 123, 212, 170, 494, 398, 581,  62, 139, 305, 147,
       191, 299, 140, 443, 512,  16, 532, 528, 513,  63, 472, 303, 189,
       213, 174, 544,  73, 480, 470, 188,  39, 193, 547, 477, 150, 145,
       210, 446, 306,  20, 467, 231, 283, 224, 178, 203,  87, 152, 219,
       511, 266, 493, 461, 323, 263,   6,  14,  67,  75, 392, 265,   1,
       338, 315, 541, 560,  68, 471, 358, 449, 537, 216,  34, 545, 243,
        32, 444, 403, 462, 308, 207, 271, 590, 238,  17, 228,  69, 478,
       144,  61, 313, 310, 127, 568,   2, 394, 353,  84, 414, 421, 439,
        98,   0,  15, 565,  24, 300, 349, 484, 136, 234, 169,  65, 427,
        47,  80, 489, 466, 536, 406, 126, 155, 361,  74, 386,  83, 515,
       249, 397, 105, 422, 559, 492, 551, 409, 387, 425, 430, 259, 431,
       345, 258, 254, 570, 146,  78, 320, 400, 586, 500, 251, 158, 571,
       550, 378,  88, 474, 129, 133, 585, 297, 192, 230, 521, 463, 417,
       195, 587, 302,  40, 337, 110], dtype=int64)}
{'N.I.C': array([ 8, 62, 40, 69, 59, 52, 29, 60, 55, 41, 33, 24, 16, 67, 20,  9, 32,
       22, 18, 39, 65, 31, 35, 37, 27,  7, 49, 45, 21, 28, 26, 57, 34, 11,
       54, 50, 25,  6, 17, 30, 70, 12, 13, 56, 68, 61, 10, 47, 38, 43, 14,
       44, 48, 36, 53, 64,  5, 42, 58, 15, 19, 66, 63, 46, 51, 23],
      dtype=int64)}
{'N.I.I': array([22, 40, 52, 66, 42, 65, 13, 45, 28, 19, 26, 29, 27, 17, 15, 68, 31,
       24,  9, 21,  6, 48, 43, 12, 64, 54, 18, 56, 25, 59, 69, 49, 70, 34,
       46, 39, 41, 36, 38,  7, 35, 67, 14, 53, 37, 62, 47, 20,  5, 57, 32,
       33, 58, 61, 60, 23, 55, 10, 50, 44, 63, 11, 30, 51,  8, 16],
      dtype=int64)}
{'S.P.I': array([69., 47., 57., 59., 74., 25., 52., 79., 88., 54., 58., 89., 72.,
       65., 26., 85., 82., 31., 70., 78., 24., 27., 23., 62., 90., 64.,
       48., 60., 84., 40., 21., 51., 66., 20., 37., 45., 83., 39., 56.,
       53., 55., 22., 81., 71., 43., 61., 34., 68., 38., 46., 41., 42.,
       75., 73., 35., 77., 87., 32., 80., 63., 76., 67., 36., 28., 29.,
       50., 86., 33., 44., 30., 49.])}
{'S.P.C': array([88, 81, 13, 10, 20, 46, 61, 24, 84, 63, 12, 48, 40, 25, 83, 22, 43,
       32, 89, 15,  6, 17, 82, 52, 74, 62, 71, 38, 64, 44, 53, 49,  9,  8,
        7, 69, 77, 70, 50, 16, 67, 47, 85, 57, 35, 42, 34, 79, 39, 51, 19,
       56, 18, 14, 78, 75, 76, 29, 60, 28, 36, 30,  5, 59, 11, 68, 54, 33,
       23, 86, 21, 80, 90, 55, 66, 45, 65, 73, 37, 58, 87, 31, 26, 72, 41,
       27], dtype=int64)}
{'L.A.C': array([ 5,  1,  7, 10, 11, 15, 13, 14,  9, 12,  8,  6,  4,  3,  2],
      dtype=int64)}
{'L.A.I': array([19.,  9., 15.,  4., 13.,  3., 18., 14.,  1., 17., 10., 16.,  5.,
        2.,  8., 12.,  6.,  7., 11., 20.])}
{'Q.A': array([4., 7., 3., 6., 5., 2.])}
{'P.E.I': array(['Positive', 'Negative', 'Neutral'], dtype=object)}
{'P.E.C': array(['Negative', 'Neutral', 'Positive'], dtype=object)}
{'COMPLIANCE Ratio': array([ 24.,  99.,  16.,  66.,  47.,   5.,  13.,  30.,  49.,  72.,  41.,
        48.,  65.,  33.,  74.,  17.,  20.,  43.,  23.,  86.,  98.,   3.,
        78.,  69.,  52.,   0.,  70.,  75.,  11., 100.,  45.,   8.,  18.,
        42.,  87.,  92.,  32.,  68.,  94.,  71.,  53.,  44.,  14.,  95.,
        93.,  29.,  80.,  51.,   4.,  58.,  12.,   6.,  84.,  64.,  67.,
        77.,  21.,  34.,  73.,  79.,  60.,  96.,  46.,  63.,   7.,  25.,
        88.,  76.,  62.,  50.,  35.,  59.,  36.,  39.,  10.,   2.,  40.,
        85.,  38.,  81.,  90.,  31.,  19.,  15.,  27.,   1.,   9.,  89.,
        55.,  91.,  22.,  37.,  97.,  26.,  56.,  82.,  28.,  61.,  54.,
        57.,  83.])}
{'Interview duration': array([49, 24, 16, 40, 38, 35, 20, 46, 34, 41, 27, 29, 22, 59, 55, 45, 58,
       19, 42, 60, 56, 31, 53, 50, 54, 48, 18, 36, 37, 26, 33, 44, 43, 21,
       51, 47, 57, 30, 25, 39, 32, 52, 23, 15, 17, 28], dtype=int64)}
{'Interviewer Intro': array(['Yes', 'No'], dtype=object)}
{'Candidate into': array(['Yes', 'No'], dtype=object)}
{'Opp to ask': array(['Yes', 'No'], dtype=object)}

In [8]:
#create X and Y
X=train_df.iloc[:,0:-1]
Y=train_df.iloc[:,-1]

In [36]:
print(X.shape)
print(Y.shape)

(5790, 23)
(5790,)

In [9]:
colname=[]
for x in train_df.columns[:-1]:
    if train_df[x].dtype=='object':
        colname.append(x)
colname

['Profile',
 'P.E.I',
 'P.E.C',
 'Interviewer Intro',
 'Candidate into',
 'Opp to ask']

In [38]:
X.head()

,Profile,S.L.R.C,S.L.R.I,A.T.T,L.M.I,L.M.C,S.R,L.J.T.C,L.J.T.I,N.I.C,N.I.I,S.P.I,S.P.C,L.A.C,L.A.I,Q.A,P.E.I,P.E.C,COMPLIANCE Ratio,Interview duration,Interviewer Intro,Candidate into,Opp to ask
Interview Id,,,,,,,,,,,,,,,,,,,,,,,
6.913030e+11,Developer,0.98,0.02,53,88,93,32,88,106,41,66,42,47,13,15,6,Neutral,Neutral,98,37,No,Yes,Yes
9.214326e+11,Sales,0.67,0.33,51,53,44,36,93,313,28,62,32,52,5,15,4,Neutral,Negative,54,33,No,No,Yes
4.718839e+10,Program Manager,0.81,0.19,60,77,75,54,52,67,26,14,57,34,4,7,3,Positive,Positive,31,58,No,Yes,No
9.943741e+11,Marketing,0.69,0.31,93,42,103,49,115,166,62,55,65,75,10,10,7,Positive,Negative,24,35,No,Yes,No
3.509007e+11,QA Automation,0.57,0.43,44,44,119,66,190,394,7,32,36,74,13,7,3,Negative,Positive,73,60,Yes,Yes,No

In [10]:
# For preprocessing the data
from sklearn.preprocessing import LabelEncoder
 
le=LabelEncoder()
 
for x in colname:
    X[x]=le.fit_transform(X[x]) #mandatory
    

    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_))) #optional check labels
    print('Feature', x)
    print('mapping', le_name_mapping)

Feature Profile
mapping {'Account Manager': 0, 'Data Scientist': 1, 'Developer': 2, 'HR': 3, 'Marketing': 4, 'Product Manager': 5, 'Program Manager': 6, 'QA Automation': 7, 'QA Manual': 8, 'Sales': 9}
Feature P.E.I
mapping {'Negative': 0, 'Neutral': 1, 'Positive': 2}
Feature P.E.C
mapping {'Negative': 0, 'Neutral': 1, 'Positive': 2}
Feature Interviewer Intro
mapping {'No': 0, 'Yes': 1}
Feature Candidate into
mapping {'No': 0, 'Yes': 1}
Feature Opp to ask
mapping {'No': 0, 'Yes': 1}

In [40]:
X.head()

,Profile,S.L.R.C,S.L.R.I,A.T.T,L.M.I,L.M.C,S.R,L.J.T.C,L.J.T.I,N.I.C,N.I.I,S.P.I,S.P.C,L.A.C,L.A.I,Q.A,P.E.I,P.E.C,COMPLIANCE Ratio,Interview duration,Interviewer Intro,Candidate into,Opp to ask
Interview Id,,,,,,,,,,,,,,,,,,,,,,,
6.913030e+11,2,0.98,0.02,53,88,93,32,88,106,41,66,42,47,13,15,6,1,1,98,37,0,1,1
9.214326e+11,9,0.67,0.33,51,53,44,36,93,313,28,62,32,52,5,15,4,1,0,54,33,0,0,1
4.718839e+10,6,0.81,0.19,60,77,75,54,52,67,26,14,57,34,4,7,3,2,2,31,58,0,1,0
9.943741e+11,4,0.69,0.31,93,42,103,49,115,166,62,55,65,75,10,10,7,2,0,24,35,0,1,0
3.509007e+11,7,0.57,0.43,44,44,119,66,190,394,7,32,36,74,13,7,3,0,2,73,60,1,1,0

In [11]:
colname1=[]
for x in test_df.columns:
    if test_df[x].dtype=='object':
        colname1.append(x)
colname1

['Profile',
 'P.E.I',
 'P.E.C',
 'Interviewer Intro',
 'Candidate into',
 'Opp to ask']

In [12]:
# For preprocessing the data
from sklearn.preprocessing import LabelEncoder
 
le1=LabelEncoder()
 
for x in colname1:
    test_df[x]=le1.fit_transform(test_df[x]) #mandatory
    

    le1_name_mapping = dict(zip(le1.classes_, le1.transform(le1.classes_))) #optional check labels
    print('Feature', x)
    print('mapping', le1_name_mapping)

Feature Profile
mapping {'Account Manager': 0, 'Data Scientist': 1, 'Developer': 2, 'HR': 3, 'Marketing': 4, 'Product Manager': 5, 'Program Manager': 6, 'QA Automation': 7, 'QA Manual': 8, 'Sales': 9}
Feature P.E.I
mapping {'Negative': 0, 'Neutral': 1, 'Positive': 2}
Feature P.E.C
mapping {'Negative': 0, 'Neutral': 1, 'Positive': 2}
Feature Interviewer Intro
mapping {'No': 0, 'Yes': 1}
Feature Candidate into
mapping {'No': 0, 'Yes': 1}
Feature Opp to ask
mapping {'No': 0, 'Yes': 1}

In [13]:
from sklearn.preprocessing import StandardScaler
 
scaler=StandardScaler()
scaler.fit(X)             
X=scaler.transform(X)
print(X)

[[-0.86164066  1.60661481 -1.60661481 ... -0.99586348  1.01286338
   0.98016219]
 [ 1.56351878 -0.54263498  0.54263498 ... -0.99586348 -0.98729998
   0.98016219]
 [ 0.52416473  0.42799396 -0.42799396 ... -0.99586348  1.01286338
  -1.02023932]
 ...
 [ 0.17771339 -0.75062689  0.75062689 ... -0.99586348  1.01286338
  -1.02023932]
 [ 1.56351878  1.32929225 -1.32929225 ...  1.0041537   1.01286338
   0.98016219]
 [-0.86164066  0.56665523 -0.56665523 ... -0.99586348 -0.98729998
  -1.02023932]]

In [44]:
Y.value_counts()

Status
Consider        2309
May Consider    1886
Not Consider    1595
Name: count, dtype: int64

In [45]:
X.shape

(5790, 23)

In [14]:
test_df_scale=scaler.transform(test_df)
print(test_df_scale)

[[ 0.17771339 -1.58259455  1.58259455 ...  1.0041537   1.01286338
   0.98016219]
 [ 0.17771339  0.84397779 -0.84397779 ... -0.99586348  1.01286338
   0.98016219]
 [ 0.87061608 -1.02794945  1.02794945 ...  1.0041537  -0.98729998
   0.98016219]
 ...
 [-0.51518931 -0.12665115  0.12665115 ...  1.0041537   1.01286338
  -1.02023932]
 [-0.86164066  1.39862289 -1.39862289 ... -0.99586348 -0.98729998
  -1.02023932]
 [ 1.56351878  1.53728417 -1.53728417 ... -0.99586348 -0.98729998
   0.98016219]]

In [47]:
test_df_scale.shape

(1187, 23)

In [15]:
#train set and validation set split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [49]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(4632, 23)
(4632,)
(1158, 23)
(1158,)

In [50]:
from sklearn.tree import DecisionTreeClassifier
#create a model object
model_DecisionTree = DecisionTreeClassifier(random_state=10,criterion='gini')
# train the model object
model_DecisionTree.fit(x_train,y_train) #trainig phase is building the DTree fit Tree

y_pred=model_DecisionTree.predict(x_test)
print(y_pred)

['Consider' 'Not Consider' 'Not Consider' ... 'Consider' 'Consider'
 'May Consider']

In [51]:
model_DecisionTree.score(x_train, y_train)

1.0

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,y_pred))
 
acc=accuracy_score(y_test, y_pred)
print("Accuracy of the model: ",acc)

[[414  38   0]
 [ 34 307  45]
 [  0  39 281]]
Classification report:
              precision    recall  f1-score   support

    Consider       0.92      0.92      0.92       452
May Consider       0.80      0.80      0.80       386
Not Consider       0.86      0.88      0.87       320

    accuracy                           0.87      1158
   macro avg       0.86      0.86      0.86      1158
weighted avg       0.87      0.87      0.87      1158

Accuracy of the model:  0.8652849740932642

In [53]:
sample=pd.DataFrame()
 
sample["Column"]=train_df.columns[0:-1]
sample["Imp value"]=model_DecisionTree.feature_importances_
 
sample.sort_values("Imp value",ascending=False)

                Column  Imp value
7              L.J.T.C   0.584269
12               S.P.C   0.117411
9                N.I.C   0.082989
5                L.M.C   0.077903
19  Interview duration   0.052002
3                A.T.T   0.010031
13               L.A.C   0.008885
8              L.J.T.I   0.008069
11               S.P.I   0.007783
4                L.M.I   0.007597
18    COMPLIANCE Ratio   0.007379
1              S.L.R.C   0.006250
14               L.A.I   0.005847
10               N.I.I   0.005469
6                  S.R   0.005208
2              S.L.R.I   0.004647
15                 Q.A   0.002248
16               P.E.I   0.002074
0              Profile   0.001425
17               P.E.C   0.001093
21      Candidate into   0.000929
20   Interviewer Intro   0.000492
22          Opp to ask   0.000000

In [54]:
#last 3 cols less imp acc to DTree
# opp to ask 0% imp

In [55]:
# predicting using the Decision_Tree_classifier
from sklearn.tree import DecisionTreeClassifier

model_DT = DecisionTreeClassifier(random_state=10,
                                  criterion='gini',
                                 splitter="best",
                                 min_samples_leaf=3,
                                 min_samples_split=5,
                                 max_depth=10,
                                  max_leaf_nodes=100,
                                  #max_features=0.6
                                 )
# min_samples_leaf , min_samples_split, max_depth, max_features, max_leaf_nodes

# fit the model on the data and predict the values
model_DT.fit(x_train,y_train)
Y_pred1=model_DT.predict(x_test)
# print(list(zip(Y_test,Y_pred)))
#print(list(zip(Y_test,Y_pred)))

In [56]:
model_DT.score(x_train, y_train)

0.9488341968911918

In [57]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,Y_pred1)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,Y_pred1))
 
acc=accuracy_score(y_test, Y_pred1)
print("Accuracy of the model: ",acc)

[[409  43   0]
 [ 28 321  37]
 [  0  34 286]]
Classification report:
              precision    recall  f1-score   support

    Consider       0.94      0.90      0.92       452
May Consider       0.81      0.83      0.82       386
Not Consider       0.89      0.89      0.89       320

    accuracy                           0.88      1158
   macro avg       0.88      0.88      0.88      1158
weighted avg       0.88      0.88      0.88      1158

Accuracy of the model:  0.8773747841105354

In [58]:
#Prunned DTree is better 87

In [59]:
#try grid search cv

In [60]:
from sklearn.ensemble import RandomForestClassifier
#create a model object
model_RandomForest = RandomForestClassifier(random_state=10,n_estimators=100,bootstrap=True,n_jobs=-1)
# train the model object
model_RandomForest.fit(x_train,y_train) #trainig phase is building the DTree Trees 100

y_pred_forest=model_RandomForest.predict(x_test)
#print(y_pred_forest)

In [61]:
model_RandomForest.score(x_train, y_train)

1.0

In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,y_pred_forest)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,y_pred_forest))
 
acc=accuracy_score(y_test, y_pred_forest)
print("Accuracy of the model: ",acc)

[[415  37   0]
 [ 39 315  32]
 [  0  31 289]]
Classification report:
              precision    recall  f1-score   support

    Consider       0.91      0.92      0.92       452
May Consider       0.82      0.82      0.82       386
Not Consider       0.90      0.90      0.90       320

    accuracy                           0.88      1158
   macro avg       0.88      0.88      0.88      1158
weighted avg       0.88      0.88      0.88      1158

Accuracy of the model:  0.8799654576856649

In [63]:
from sklearn.tree import DecisionTreeClassifier
 
model_DT1= DecisionTreeClassifier(random_state=10) #fixed parameters should be passsed here
 
#parameters for trial and error should be passed here
parameter_space = {
          #np.arange(100, 1001,50),
    'max_depth':[10,15,8, 12],
    'min_samples_leaf':[1,3,4,5,6,7]
    }
from sklearn.model_selection import GridSearchCV #RandomizedSearchCV
clf = GridSearchCV(model_DT1, parameter_space, n_jobs=-1, cv=5) #cv=5 means 5 fold cv

In [64]:
clf.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=10), n_jobs=-1,
             param_grid={'max_depth': [10, 15, 8, 12],
                         'min_samples_leaf': [1, 3, 4, 5, 6, 7]})

In [65]:
print('best parameters found:\n',clf.best_params_)

best parameters found:
 {'max_depth': 10, 'min_samples_leaf': 5}

In [66]:
clf.best_score_  #cv accuracy list avg score - cv score

0.874134962406891

In [67]:
y_pred_clf=clf.predict(x_test)

In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,y_pred_clf)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,y_pred_clf))
 
acc=accuracy_score(y_test, y_pred_clf)
print("Accuracy of the model: ",acc)

[[412  40   0]
 [ 41 306  39]
 [  0  35 285]]
Classification report:
              precision    recall  f1-score   support

    Consider       0.91      0.91      0.91       452
May Consider       0.80      0.79      0.80       386
Not Consider       0.88      0.89      0.89       320

    accuracy                           0.87      1158
   macro avg       0.86      0.86      0.86      1158
weighted avg       0.87      0.87      0.87      1158

Accuracy of the model:  0.8661485319516408

In [69]:
from sklearn.ensemble import RandomForestClassifier
 
model_RF1= RandomForestClassifier(random_state=10, bootstrap=True) #fixed parameters should be passsed here
 
#parameters for trial and error should be passed here
parameter_space = {
    'n_estimators':[100,300,500],       #np.arange(100, 1001,50),
    'max_depth':[10,15,8, 12],
    'min_samples_leaf':[1,3,4,5,6,7]
    }
from sklearn.model_selection import GridSearchCV #RandomizedSearchCV
clf1 = GridSearchCV(model_RF1, parameter_space, n_jobs=-1, cv=5) #cv=5 means 5 fold cv

In [70]:
clf1.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=10), n_jobs=-1,
             param_grid={'max_depth': [10, 15, 8, 12],
                         'min_samples_leaf': [1, 3, 4, 5, 6, 7],
                         'n_estimators': [100, 300, 500]})

In [71]:
print('best parameters found:\n',clf1.best_params_)

best parameters found:
 {'max_depth': 15, 'min_samples_leaf': 1, 'n_estimators': 300}

In [72]:
clf1.best_score_  #cv accuracy list avg score - cv score

0.8996125358515009

In [73]:
y_pred_clf1=clf1.predict(x_test)

In [74]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,y_pred_clf1)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,y_pred_clf1))
 
acc=accuracy_score(y_test, y_pred_clf1)
print("Accuracy of the model: ",acc)

[[415  37   0]
 [ 44 313  29]
 [  0  26 294]]
Classification report:
              precision    recall  f1-score   support

    Consider       0.90      0.92      0.91       452
May Consider       0.83      0.81      0.82       386
Not Consider       0.91      0.92      0.91       320

    accuracy                           0.88      1158
   macro avg       0.88      0.88      0.88      1158
weighted avg       0.88      0.88      0.88      1158

Accuracy of the model:  0.8825561312607945

In [88]:
from sklearn.ensemble import ExtraTreesClassifier
 
model_EXT= ExtraTreesClassifier(random_state=10, bootstrap=True) #fixed parameters should be passsed here
 
#parameters for trial and error should be passed here
parameter_space = {
    'n_estimators':[100,300,350,400,500],       #np.arange(100, 1001,50),
    'max_depth':[10,15,8, 12],
    'min_samples_leaf':[1,3,4,5,6,7]
    }
from sklearn.model_selection import GridSearchCV #RandomizedSearchCV
clf2 = GridSearchCV(model_EXT, parameter_space, n_jobs=-1, cv=5) #cv=5 means 5 fold cv

In [89]:
clf2.fit(x_train,y_train)

GridSearchCV(cv=5,
             estimator=ExtraTreesClassifier(bootstrap=True, random_state=10),
             n_jobs=-1,
             param_grid={'max_depth': [10, 15, 8, 12],
                         'min_samples_leaf': [1, 3, 4, 5, 6, 7],
                         'n_estimators': [100, 300, 350, 400, 500]})

In [90]:
print('best parameters found:\n',clf2.best_params_)

best parameters found:
 {'max_depth': 12, 'min_samples_leaf': 3, 'n_estimators': 500}

In [91]:
clf2.best_score_  #cv accuracy list avg score - cv score

0.8987497699213189

In [92]:
y_pred_clf2=clf2.predict(x_test)

In [93]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,y_pred_clf2)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,y_pred_clf2))
 
acc=accuracy_score(y_test, y_pred_clf2)
print("Accuracy of the model: ",acc)

[[432  20   0]
 [ 57 298  31]
 [  0  29 291]]
Classification report:
              precision    recall  f1-score   support

    Consider       0.88      0.96      0.92       452
May Consider       0.86      0.77      0.81       386
Not Consider       0.90      0.91      0.91       320

    accuracy                           0.88      1158
   macro avg       0.88      0.88      0.88      1158
weighted avg       0.88      0.88      0.88      1158

Accuracy of the model:  0.8816925734024179

In [75]:
from sklearn.linear_model import LogisticRegression
#create a model object
classifier = LogisticRegression()
#train the model object
classifier.fit(x_train, y_train)

#print intercepts and coefficients
print(classifier.intercept_)
print(classifier.coef_)

[ 0.22261242  4.61598695 -4.83859937]
[[-8.36327504e-02 -1.37644872e-02  1.37644872e-02  2.13226018e-02
  -8.59014102e-02  3.24887552e+00 -6.99986202e-02 -1.21568781e+01
  -3.62789821e-03 -2.63835946e+00  4.48185167e-02 -3.73465318e-02
   3.43794499e+00 -6.31118736e-01 -5.63137652e-02 -5.16747235e-03
   8.81221945e-03 -3.19650247e-02 -5.95244906e-02  1.82651382e+00
  -8.66007191e-02 -2.32991595e-02  1.53334980e-02]
 [-4.57753430e-03  4.83543148e-03 -4.83543148e-03 -8.28770764e-06
   4.06444796e-02  1.92541606e-02 -1.39395054e-02  7.91985872e-02
   1.66015078e-02  5.48254196e-03 -2.03660734e-02  4.12288141e-03
   5.20826963e-02  3.29185764e-02  1.09608408e-02 -1.68630317e-02
  -7.21447661e-03  1.26799919e-02  2.21382305e-02 -3.34419906e-02
   4.43371759e-02  4.17996119e-03 -3.05830446e-02]
 [ 8.82102847e-02  8.92905574e-03 -8.92905574e-03 -2.13143141e-02
   4.52569306e-02 -3.26812968e+00  8.39381256e-02  1.20776795e+01
  -1.29736096e-02  2.63287692e+00 -2.44524433e-02  3.32236503e-02
  -3.49002769e+00  5.98200159e-01  4.53529244e-02  2.20305040e-02
  -1.59774284e-03  1.92850328e-02  3.73862601e-02 -1.79307183e+00
   4.22635431e-02  1.91191983e-02  1.52495466e-02]]

In [76]:
Y_pred_logistic = classifier.predict(x_test)
print(Y_pred_logistic)

['May Consider' 'Not Consider' 'Not Consider' ... 'Consider' 'Consider'
 'May Consider']

In [77]:
Y_pred_prob = classifier.predict_proba(x_test)
print(Y_pred_prob)
#This is a probability matrix which tells us the probability of a variable belonging to class 0 and class 1.
#Default threshold is 0.5
#So if we see class 0 beats the threshold value.

[[1.87947046e-01 8.12050292e-01 2.66242558e-06]
 [6.20574456e-08 2.05237931e-01 7.94762007e-01]
 [2.59863133e-16 2.57583850e-05 9.99974242e-01]
 ...
 [9.89563074e-01 1.04369261e-02 1.08925347e-10]
 [9.98664164e-01 1.33583577e-03 2.16602731e-12]
 [4.38196150e-03 9.95479322e-01 1.38716195e-04]]

In [78]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,Y_pred_logistic)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,Y_pred_logistic))
 
acc=accuracy_score(y_test, Y_pred_logistic)
print("Accuracy of the model: ",acc)

[[446   6   0]
 [  1 381   4]
 [  0   3 317]]
Classification report:
              precision    recall  f1-score   support

    Consider       1.00      0.99      0.99       452
May Consider       0.98      0.99      0.98       386
Not Consider       0.99      0.99      0.99       320

    accuracy                           0.99      1158
   macro avg       0.99      0.99      0.99      1158
weighted avg       0.99      0.99      0.99      1158

Accuracy of the model:  0.9879101899827288

In [79]:
np.set_printoptions(suppress = True)

In [80]:
Y_pred_prob = classifier.predict_proba(x_test)
print(Y_pred_prob)

[[0.18794705 0.81205029 0.00000266]
 [0.00000006 0.20523793 0.79476201]
 [0.         0.00002576 0.99997424]
 ...
 [0.98956307 0.01043693 0.        ]
 [0.99866416 0.00133584 0.        ]
 [0.00438196 0.99547932 0.00013872]]

In [81]:
classifier.score(x_train, y_train)

0.9950345423143351

In [82]:
# Test file predictions using logistic Regression

In [83]:
Y_pred_test_file = classifier.predict(test_df_scaled)
print(Y_pred_test_file)

['Consider' 'Not Consider' 'Not Consider' ... 'Not Consider'
 'Not Consider' 'Not Consider']

In [84]:
len(Y_pred_test_file)

1187

In [85]:
test_df.shape

(1187, 23)

In [86]:
Predictions_df=pd.DataFrame(test_df.index,columns=['Interview Id'])
Predictions_df['Candidate Interview Status Predictions']=Y_pred_test_file
Predictions_df

      Interview Id Candidate Interview Status Predictions
0     702127796635                               Consider
1     613490569071                           Not Consider
2     759998772623                           Not Consider
3     391760082113                           Not Consider
4     941599210196                           Not Consider
...            ...                                    ...
1182  256033687434                           Not Consider
1183  627337316047                           Not Consider
1184   75547031851                           Not Consider
1185  173914777164                           Not Consider
1186  480519602140                           Not Consider

[1187 rows x 2 columns]

In [87]:
#Predictions_df.to_csv('Candidate Interview Status Predictions.csv',index=False,header=True)